language: python

python: 2.7

install:
  - pip install -r requirements/development.txt
  - python manage.py syncdb --noinput
  - python manage.py migrate


script:
  - py.test tests/ -v 


notifications:
  irc:
    channels: "irc.freenode.org#baroque-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always

  email:
    on_success: change
    on_failure: change