sudo: required
dist: trusty
language: python
python:
  - "3.4"
env:
  - DJANGO_SETTINGS_MODULE=webapp.settings.travis

addons:
  postgresql: "9.3"
  apt:
    packages:
      - libappindicator1
      - fonts-liberation

before_install:
  - psql -c 'create database vmprof;' -U postgres
install:
  - pip install -r requirements/testing.txt

script:
  - py.test . -v

notifications:
  irc:
    channels: "irc.freenode.org#baroque-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always

  email:
    on_success: change
    on_failure: change
