language: python

python: 2.7

addons:
  postgresql: "9.3"

before_install:
  - psql -c 'create database vmprof;' -U postgres
  
install:
  - pip install -r requirements/development.txt
  - python manage.py syncdb --noinput
  - python manage.py migrate


script:
  - py.test tests/ -v 


notifications:
  irc:
    channels: "irc.freenode.org#baroque-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always

  email:
    on_success: change
    on_failure: change